[profile.default]
solc_version = '0.8.17' # Version of solc that we use
remappings = [ # Libraries that we use from node_modules and are used by the smart contracts
  "@openzeppelin/=lib/openzeppelin-contracts/",
  "forge-std/=lib/forge-std/src/",
]
optimizer = true # Enable or disable the solc optimizer
optimizer_runs = 999999 # The number of optimizer runs
verbosity = 3 # The verbosity of tests
bytecode_hash = "none" # For deterministic code
block_timestamp = 1622400000 # Timestamp for tests (non-zero)

# silence warnings
# 2462 - ignored constructor visibility in OZ dependency
# 5868 - Failure condition of 'send' ignored in bridge
# 9302 - Failure condition of 'call' ignored in bridge
ignored_error_codes = [2462, 5878, 9302]
libs = ["node_modules", "lib"]

[rpc_endpoints]
provider = "${PROVIDER}"

[fuzz]
# The number of fuzz runs for fuzz tests
runs = 10000

[invariant]
runs = 1000 #default 256
depth = 23 # default 15
fail_on_revert = false # default false
